apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerroyale
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burgerroyale
    spec:
      containers:
        - name: burgerroyale
          image: ${IMAGE_URI}
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: ConnectionStrings__DefaultConnection
              value: Server=${DB_ADDRESS},1433;Database=${DB_NAME};User Id=${DB_USER};TrustServerCertificate=True;Password=${DB_PASSWORD};
            - name: Jwt__Issuer
              value: ${JWT_ISSUER}
            - name: Jwt__Audience
              value: ${JWT_AUDIENCE}
            - name: Jwt__SecretKey
              value: ${JWT_SECRETKEY}
            - name: AWS__AccessKey
              value: ${AWS_ACCESS_KEY}
            - name: AWS__SecretKey
              value: ${AWS_SECRET_ACCESS_KEY}
            - name: AWS__SessionToken
              value: ${AWS_SESSION_TOKEN}
            - name: AWS__Region
              value: ${AWS_REGION}

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
  selector:
    matchLabels:
      app: burgerroyale