apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerroyale
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burgerroyale
    spec:
      containers:
        - name: burgerroyale
          image: ${IMAGE_URI}
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: BurgerRoyale__BaseUrl
              value: "http://burgerroyale:5000"

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
  selector:
    matchLabels:
      app: burgerroyale