name: Pipeline

on:
  push:
    branches: [ "main", "develop", "pipeline-2"]
  pull_request:
    branches: [ "main", "develop"]
  
env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Tests
      run: |
        cd tests/BurgerRoyale.UnitTests
        dotnet test
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_RAFFA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_RAFFA }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_RAFFA }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: burgerroyale
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        echo ${{ steps.login-ecr.outputs.registry }}
        echo ${{ steps.commit.outputs.short }}
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f docker/Dockerfile .
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker build -t 992382425825.dkr.ecr.us-east-1.amazonaws.com/burgerroyale:latest  .
        docker push 992382425825.dkr.ecr.us-east-1.amazonaws.com/burgerroyale:latest